name: Sync to Hugging Space
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync_to_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      - name: Ignore large files
        run : git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch "Rag_Documents/layout-parser-paper.pdf"' HEAD
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://priyasmita:$HF_TOKEN@huggingface.co/spaces/priyasmita/agenticAI main